# Generated by Django 4.2.7 on 2023-12-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=240)),
                ('email', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=240)),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(1, 'Diagnostic Equipment'), (2, 'Monitoring Equipment'), (3, 'Surgical Equipment'), (4, 'Laboratory Equipment'), (5, 'Patient Care Equipment'), (6, 'Orthopedic Equipment')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('equipment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_equipment', to='company.equipment')),
                ('reservation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_equipment', to='company.equipmentreservation')),
            ],
        ),
        migrations.CreateModel(
            name='PickupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_firstName', models.CharField(default='', max_length=30)),
                ('administrator_lastName', models.CharField(default='', max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_schedules', to='company.company')),
            ],
        ),
    ]
