# Generated by Django 4.2.7 on 2023-11-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
