# Generated by Django 4.2.7 on 2023-11-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(default='', max_length=240),
        ),
    ]
