# Generated by Django 4.2.7 on 2023-11-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Company_Equipment',
        ),
    ]
