# Generated by Django 4.2.7 on 2023-12-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_equipment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupschedule',
            name='administrator_name',
        ),
        migrations.AddField(
            model_name='pickupschedule',
            name='administrator_firstName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickupschedule',
            name='administrator_lastName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
