# Generated by Django 4.2.7 on 2024-01-31 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupschedule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_schedule_company', to='company.company'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default='2024-01-01 00:00:00')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_company', to='company.company')),
                ('equipment', models.ManyToManyField(to='company.equipment')),
            ],
        ),
    ]
