# Generated by Django 4.2.7 on 2023-11-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_equipmentreservation_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentreservation',
            name='equipment',
        ),
        migrations.CreateModel(
            name='ReservedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('equipment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_equipment', to='company.equipment')),
                ('reservation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_equipment', to='company.equipmentreservation')),
            ],
        ),
    ]
