# Generated by Django 4.2.7 on 2023-11-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_equipment_company_id_equipment_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='company_id',
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='company.company'),
        ),
    ]
