# Generated by Django 4.2.7 on 2024-01-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_pickupschedule_company_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='equipment',
        ),
        migrations.AddField(
            model_name='contract',
            name='equipment',
            field=models.JSONField(default='{}'),
        ),
    ]
