# Generated by Django 4.2.7 on 2024-01-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_contract_equipment_contract_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='equipment',
            field=models.JSONField(default=dict),
        ),
    ]
