# Generated by Django 4.2.7 on 2023-11-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_equipmentreservation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentreservation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
