# Generated by Django 4.2.7 on 2023-11-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_schedules', to='company.company')),
            ],
        ),
    ]
