# Generated by Django 4.2.7 on 2024-01-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_contract_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
