# Generated by Django 4.2.7 on 2024-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_equipment_version_pickupschedule_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='reserved_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
